### ISSUE TITLE
Add Spanish support to the landing page.

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampSpain#7]
This is a sub-issue of #1 

The landing page needs to have a language switcher between Spanish and English.

**Comment by nuez** [comment]
@juampynr I think we can close this one.

**Comment by juampynr** [comment]
Done at http://2017.drupalcamp.es/es but needs a few adjustments:

![image](https://cloud.githubusercontent.com/assets/108130/18838210/e79abd8e-8406-11e6-818d-0192c0bce686.png)

![image](https://cloud.githubusercontent.com/assets/108130/18838237/0c4d3f30-8407-11e6-9558-f9e7e316215c.png)

![image](https://cloud.githubusercontent.com/assets/108130/18838302/47b5229a-8407-11e6-8ea9-ab491810fc56.png)

![image](https://cloud.githubusercontent.com/assets/108130/18838344/6e22e8ae-8407-11e6-87b1-d31590c1bd9b.png)

![image](https://cloud.githubusercontent.com/assets/108130/18838361/7c2c2f00-8407-11e6-8416-38f26ad81f0d.png)

**Comment by juampynr** [comment]
cc @ckrina

**Comment by ckrina** [comment]
"Únete a la comunidad" > AED++
Then we should probably change: "La Asociación Española de Drupal va augmentando.."
+1 to check other strings

Also the 2nd section still have issues with Firefox. Attaching image.
![home drupalcamp spain 2017 2016-09-26 16-49-06](https://cloud.githubusercontent.com/assets/2225966/18844435/24f4ec0a-8415-11e6-8f58-f20161b99569.png)

**Comment by juampynr** [comment]
https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/37

**Comment by nuez** [comment]
#41

**Comment by juampynr** [comment]
Closed via https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/41
